name: indoor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - pillow
  - plotly
  - psutil
  - requests
  - python-kaleido
  - scikit-learn
  - lightgbm
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pytorch-lightning
  - icecream
  - neptune-client
